// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/core/baseTable.vue')['default']
    CategoryForm: typeof import('./src/components/products/categoryForm.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/auth/login.vue')['default']
    LoginFrom: typeof import('./src/components/auth/loginFrom.vue')['default']
    Modal: typeof import('./src/components/core/modal.vue')['default']
    Navigation: typeof import('./src/components/core/navigation.vue')['default']
    PasswordChangeForm: typeof import('./src/components/auth/passwordChangeForm.vue')['default']
    PasswordRecoveryForm: typeof import('./src/components/auth/passwordRecoveryForm.vue')['default']
    PasswordRecoveryVerificationCodeForm: typeof import('./src/components/auth/passwordRecoveryVerificationCodeForm.vue')['default']
    ProductForm: typeof import('./src/components/products/productForm.vue')['default']
    ProductImages: typeof import('./src/components/products/productImages.vue')['default']
    ProductsList: typeof import('./src/components/products/productsList.vue')['default']
    RegistrationForm: typeof import('./src/components/auth/registrationForm.vue')['default']
    RolesForm: typeof import('./src/components/roles/rolesForm.vue')['default']
    RolesList: typeof import('./src/components/roles/rolesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/core/toast.vue')['default']
    User: typeof import('./src/components/auth/user.vue')['default']
    UserForm: typeof import('./src/components/users/userForm.vue')['default']
    UserProfile: typeof import('./src/components/auth/userProfile.vue')['default']
    UsersList: typeof import('./src/components/users/usersList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
