// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Categories: typeof import('./src/components/categories/index.vue')['default']
    CategoryForm: typeof import('./src/components/products/categoryForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeaderBar: typeof import('./src/components/core/headerBar.vue')['default']
    LoginFrom: typeof import('./src/components/auth/loginFrom.vue')['default']
    Navigation: typeof import('./src/components/core/navigation.vue')['default']
    NewRegistrationVerificationCode: typeof import('./src/components/auth/newRegistrationVerificationCode.vue')['default']
    OrderComponent: typeof import('./src/components/shoppingSessions/orderComponent.vue')['default']
    OrderItemComponent: typeof import('./src/components/shoppingSessions/orderItemComponent.vue')['default']
    ProductForm: typeof import('./src/components/products/productForm/index.vue')['default']
    ProductImages: typeof import('./src/components/products/productForm/productImages.vue')['default']
    ProductInventory: typeof import('./src/components/products/productForm/productInventory.vue')['default']
    ProductOtherConfigurations: typeof import('./src/components/products/productForm/productOtherConfigurations.vue')['default']
    ProductPricing: typeof import('./src/components/products/productForm/productPricing.vue')['default']
    ProductsList: typeof import('./src/components/products/productsList.vue')['default']
    ProductTitleDescription: typeof import('./src/components/products/productForm/productTitleDescription.vue')['default']
    RegistrationForm: typeof import('./src/components/auth/registrationForm.vue')['default']
    RolesForm: typeof import('./src/components/roles/rolesForm.vue')['default']
    RolesList: typeof import('./src/components/roles/rolesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/components/users/userForm.vue')['default']
    UserListItemComponent: typeof import('./src/components/shoppingSessions/userListItemComponent.vue')['default']
    UserProfile: typeof import('./src/components/core/userProfile.vue')['default']
    UsersCard: typeof import('./src/components/users/usersCard.vue')['default']
    UsersList: typeof import('./src/components/users/usersList.vue')['default']
    UsersListComponent: typeof import('./src/components/shoppingSessions/usersListComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
